export const GLOBAL_COLLAPSED = 'global/COLLAPSED';
export const GLOBAL_INPATIENT_TABLE_STYLE = 'global/INPATIENT_TABLE_STYLE';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
export const LANGUAGE_CHANGE = 'LANGUAGE_CHANGE';
