export const changwatpart: any = {
  // 99: { chwcode: '', chwname: 'ทั้งหมด' },
  1: { chwcode: '10', chwname: 'กรุงเทพมหานคร' },
  2: { chwcode: '11', chwname: 'สมุทรปราการ' },
  3: { chwcode: '12', chwname: 'นนทบุรี' },
  4: { chwcode: '13', chwname: 'ปทุมธานี' },
  5: { chwcode: '14', chwname: 'พระนครศรีอยุธยา' },
  6: { chwcode: '15', chwname: 'อ่างทอง' },
  7: { chwcode: '16', chwname: 'ลพบุรี' },
  8: { chwcode: '17', chwname: 'สิงห์บุรี' },
  9: { chwcode: '18', chwname: 'ชัยนาท' },
  10: { chwcode: '19', chwname: 'สระบุรี' },
  11: { chwcode: '20', chwname: 'ชลบุรี' },
  12: { chwcode: '21', chwname: 'ระยอง' },
  13: { chwcode: '22', chwname: 'จันทบุรี' },
  14: { chwcode: '23', chwname: 'ตราด' },
  15: { chwcode: '24', chwname: 'ฉะเชิงเทรา' },
  16: { chwcode: '25', chwname: 'ปราจีนบุรี' },
  17: { chwcode: '26', chwname: 'นครนายก' },
  18: { chwcode: '27', chwname: 'สระแก้ว' },
  19: { chwcode: '30', chwname: 'นครราชสีมา' },
  20: { chwcode: '31', chwname: 'บุรีรัมย์' },
  21: { chwcode: '32', chwname: 'สุรินทร์' },
  22: { chwcode: '33', chwname: 'ศรีสะเกษ' },
  23: { chwcode: '34', chwname: 'อุบลราชธานี' },
  24: { chwcode: '35', chwname: 'ยโสธร' },
  25: { chwcode: '36', chwname: 'ชัยภูมิ' },
  26: { chwcode: '37', chwname: 'อำนาจเจริญ' },
  27: { chwcode: '38', chwname: 'บึงกาฬ' },
  28: { chwcode: '39', chwname: 'หนองบัวลำภู' },
  29: { chwcode: '40', chwname: 'ขอนแก่น' },
  30: { chwcode: '41', chwname: 'อุดรธานี' },
  31: { chwcode: '42', chwname: 'เลย' },
  32: { chwcode: '43', chwname: 'หนองคาย' },
  33: { chwcode: '44', chwname: 'มหาสารคาม' },
  34: { chwcode: '45', chwname: 'ร้อยเอ็ด' },
  35: { chwcode: '46', chwname: 'กาฬสินธุ์' },
  36: { chwcode: '47', chwname: 'สกลนคร' },
  37: { chwcode: '48', chwname: 'นครพนม' },
  38: { chwcode: '49', chwname: 'มุกดาหาร' },
  39: { chwcode: '50', chwname: 'เชียงใหม่' },
  40: { chwcode: '51', chwname: 'ลำพูน' },
  41: { chwcode: '52', chwname: 'ลำปาง' },
  42: { chwcode: '53', chwname: 'อุตรดิตถ์' },
  43: { chwcode: '54', chwname: 'แพร่' },
  44: { chwcode: '55', chwname: 'น่าน' },
  45: { chwcode: '56', chwname: 'พะเยา' },
  46: { chwcode: '57', chwname: 'เชียงราย' },
  47: { chwcode: '58', chwname: 'แม่ฮ่องสอน' },
  48: { chwcode: '60', chwname: 'นครสวรรค์' },
  49: { chwcode: '61', chwname: 'อุทัยธานี' },
  50: { chwcode: '62', chwname: 'กำแพงเพชร' },
  51: { chwcode: '63', chwname: 'ตาก' },
  52: { chwcode: '64', chwname: 'สุโขทัย' },
  53: { chwcode: '65', chwname: 'พิษณุโลก' },
  54: { chwcode: '66', chwname: 'พิจิตร' },
  55: { chwcode: '67', chwname: 'เพชรบูรณ์' },
  56: { chwcode: '70', chwname: 'ราชบุรี' },
  57: { chwcode: '71', chwname: 'กาญจนบุรี' },
  58: { chwcode: '72', chwname: 'สุพรรณบุรี' },
  59: { chwcode: '73', chwname: 'นครปฐม' },
  60: { chwcode: '74', chwname: 'สมุทรสาคร' },
  61: { chwcode: '75', chwname: 'สมุทรสงคราม' },
  62: { chwcode: '76', chwname: 'เพชรบุรี' },
  63: { chwcode: '77', chwname: 'ประจวบคีรีขันธ์' },
  64: { chwcode: '80', chwname: 'นครศรีธรรมราช' },
  65: { chwcode: '81', chwname: 'กระบี่' },
  66: { chwcode: '82', chwname: 'พังงา' },
  67: { chwcode: '83', chwname: 'ภูเก็ต' },
  68: { chwcode: '84', chwname: 'สุราษฎร์ธานี' },
  69: { chwcode: '85', chwname: 'ระนอง' },
  70: { chwcode: '86', chwname: 'ชุมพร' },
  71: { chwcode: '90', chwname: 'สงขลา' },
  72: { chwcode: '91', chwname: 'สตูล' },
  73: { chwcode: '92', chwname: 'ตรัง' },
  74: { chwcode: '93', chwname: 'พัทลุง' },
  75: { chwcode: '94', chwname: 'ปัตตานี' },
  76: { chwcode: '95', chwname: 'ยะลา' },
  77: { chwcode: '96', chwname: 'นราธิวาส' },
};

interface IChwpart {
  chwcode: string;
  chwname: string;
}

export const CHWPART: IChwpart[] = [
  { chwcode: '10', chwname: 'กรุงเทพมหานคร' },
  { chwcode: '11', chwname: 'สมุทรปราการ' },
  { chwcode: '12', chwname: 'นนทบุรี' },
  { chwcode: '13', chwname: 'ปทุมธานี' },
  { chwcode: '14', chwname: 'พระนครศรีอยุธยา' },
  { chwcode: '15', chwname: 'อ่างทอง' },
  { chwcode: '16', chwname: 'ลพบุรี' },
  { chwcode: '17', chwname: 'สิงห์บุรี' },
  { chwcode: '18', chwname: 'ชัยนาท' },
  { chwcode: '19', chwname: 'สระบุรี' },
  { chwcode: '20', chwname: 'ชลบุรี' },
  { chwcode: '21', chwname: 'ระยอง' },
  { chwcode: '22', chwname: 'จันทบุรี' },
  { chwcode: '23', chwname: 'ตราด' },
  { chwcode: '24', chwname: 'ฉะเชิงเทรา' },
  { chwcode: '25', chwname: 'ปราจีนบุรี' },
  { chwcode: '26', chwname: 'นครนายก' },
  { chwcode: '27', chwname: 'สระแก้ว' },
  { chwcode: '30', chwname: 'นครราชสีมา' },
  { chwcode: '31', chwname: 'บุรีรัมย์' },
  { chwcode: '32', chwname: 'สุรินทร์' },
  { chwcode: '33', chwname: 'ศรีสะเกษ' },
  { chwcode: '34', chwname: 'อุบลราชธานี' },
  { chwcode: '35', chwname: 'ยโสธร' },
  { chwcode: '36', chwname: 'ชัยภูมิ' },
  { chwcode: '37', chwname: 'อำนาจเจริญ' },
  { chwcode: '38', chwname: 'บึงกาฬ' },
  { chwcode: '39', chwname: 'หนองบัวลำภู' },
  { chwcode: '40', chwname: 'ขอนแก่น' },
  { chwcode: '41', chwname: 'อุดรธานี' },
  { chwcode: '42', chwname: 'เลย' },
  { chwcode: '43', chwname: 'หนองคาย' },
  { chwcode: '44', chwname: 'มหาสารคาม' },
  { chwcode: '45', chwname: 'ร้อยเอ็ด' },
  { chwcode: '46', chwname: 'กาฬสินธุ์' },
  { chwcode: '47', chwname: 'สกลนคร' },
  { chwcode: '48', chwname: 'นครพนม' },
  { chwcode: '49', chwname: 'มุกดาหาร' },
  { chwcode: '50', chwname: 'เชียงใหม่' },
  { chwcode: '51', chwname: 'ลำพูน' },
  { chwcode: '52', chwname: 'ลำปาง' },
  { chwcode: '53', chwname: 'อุตรดิตถ์' },
  { chwcode: '54', chwname: 'แพร่' },
  { chwcode: '55', chwname: 'น่าน' },
  { chwcode: '56', chwname: 'พะเยา' },
  { chwcode: '57', chwname: 'เชียงราย' },
  { chwcode: '58', chwname: 'แม่ฮ่องสอน' },
  { chwcode: '60', chwname: 'นครสวรรค์' },
  { chwcode: '61', chwname: 'อุทัยธานี' },
  { chwcode: '62', chwname: 'กำแพงเพชร' },
  { chwcode: '63', chwname: 'ตาก' },
  { chwcode: '64', chwname: 'สุโขทัย' },
  { chwcode: '65', chwname: 'พิษณุโลก' },
  { chwcode: '66', chwname: 'พิจิตร' },
  { chwcode: '67', chwname: 'เพชรบูรณ์' },
  { chwcode: '70', chwname: 'ราชบุรี' },
  { chwcode: '71', chwname: 'กาญจนบุรี' },
  { chwcode: '72', chwname: 'สุพรรณบุรี' },
  { chwcode: '73', chwname: 'นครปฐม' },
  { chwcode: '74', chwname: 'สมุทรสาคร' },
  { chwcode: '75', chwname: 'สมุทรสงคราม' },
  { chwcode: '76', chwname: 'เพชรบุรี' },
  { chwcode: '77', chwname: 'ประจวบคีรีขันธ์' },
  { chwcode: '80', chwname: 'นครศรีธรรมราช' },
  { chwcode: '81', chwname: 'กระบี่' },
  { chwcode: '82', chwname: 'พังงา' },
  { chwcode: '83', chwname: 'ภูเก็ต' },
  { chwcode: '84', chwname: 'สุราษฎร์ธานี' },
  { chwcode: '85', chwname: 'ระนอง' },
  { chwcode: '86', chwname: 'ชุมพร' },
  { chwcode: '90', chwname: 'สงขลา' },
  { chwcode: '91', chwname: 'สตูล' },
  { chwcode: '92', chwname: 'ตรัง' },
  { chwcode: '93', chwname: 'พัทลุง' },
  { chwcode: '94', chwname: 'ปัตตานี' },
  { chwcode: '95', chwname: 'ยะลา' },
  { chwcode: '96', chwname: 'นราธิวาส' },
];
